name: 更新 CCTV5+ 动态链接

on:
  schedule:
    - cron: "0 */3 * * *"   # 每3小时运行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v2

      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: 安装依赖
        run: pip install requests

      - name: 运行脚本获取链接
        run: python fetch_migu.py

      - name: 提交更新
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
