name: Update Migu Playlist

on:
  schedule:
    - cron: "0 */3 * * *"   # 每3小时执行一次
  workflow_dispatch:         # 手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_migu.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add migu.m3u
          git commit -m "Update migu.m3u" || echo "No changes"
          git push
